# Generated by Django 5.1 on 2024-10-12 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0038_alter_post_status_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='posted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('Chờ gửi', 'Chờ gửi'), ('Chờ duyệt', 'Chờ duyệt'), ('Từ chối', 'Từ chối'), ('Chờ sửa', 'Chờ sửa'), ('Chờ đăng', 'Chờ đăng'), ('Đã đăng', 'Đã đăng')], default='Chờ gửi', max_length=20),
        ),
    ]
